spring:
  profiles:
    active:
      dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-ghh-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-ghh-test